{
 "title": "BBox Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (instance)(rate(bb_device_cpu_user[5m])) * 100",
     "legendFormat": "User"
    },
    {
     "expr": "sum by (instance)(rate(bb_device_cpu_system[5m])) * 100",
     "legendFormat": "System"
    },
    {
     "expr": "sum by (instance)(rate(bb_device_cpu_system[5m])) * 100 + sum by (instance)(rate(bb_device_cpu_user[5m])) * 100",
     "legendFormat": "System + User"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    { "expr": "bb_device_mem_total", "legendFormat": "Total" },
    { "expr": "bb_device_mem_free", "legendFormat": "Free" }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "WAN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(bb_wan_ip_stats_rx_bytes[5m])*8",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(bb_wan_ip_stats_tx_bytes[5m])*8",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "LAN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(bb_lan_stats_rx_bytes[5m])*8",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(bb_lan_stats_tx_bytes[5m])*8",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Wireless",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(bb_wireless_24_stats_rx_bytes[5m])*8",
     "legendFormat": "Received 2.4 GHz"
    },
    {
     "expr": "rate(bb_wireless_24_stats_tx_bytes[5m])*8",
     "legendFormat": "Transmitted 2.4 GHz"
    },
    {
     "expr": "rate(bb_wireless_5_stats_rx_bytes[5m])*8",
     "legendFormat": "Received 5 GHz"
    },
    {
     "expr": "rate(bb_wireless_5_stats_tx_bytes[5m])*8",
     "legendFormat": "Transmitted 5 GHz"
    }
   ]
  }
 ]
}